import React, { useState } from "react";

const AIAssistant: React.FC = () => {
  const [input, setInput] = useState("");
  const [log, setLog] = useState([
    { from: "ai", text: "Hello! Ask me anything you're learning today." },
  ]);

  function send() {
    if (!input) return;
    setLog([...log, { from: "me", text: input }]);
    setInput("");

    setTimeout(() => {
      setLog((prev) => [...prev, { from: "ai", text: "Here is a short answer generated by AI." }]);
    }, 600);
  }

  return (
    <div className="bg-white rounded-lg p-5 shadow">
      <h3 className="text-lg font-semibold mb-3">AI Learning Assistant</h3>

      <div className="h-64 overflow-auto border p-3 rounded bg-gray-50">
        {log.map((m, i) => (
          <div key={i} className={`${m.from === "ai" ? "text-left" : "text-right"} mb-3`}>
            <span
              className={`inline-block px-3 py-2 rounded ${
                m.from === "ai" ? "bg-white shadow" : "bg-[var(--primary)] text-white"
              }`}
            >
              {m.text}
            </span>
          </div>
        ))}
      </div>

      <div className="mt-3 flex gap-3">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          className="flex-1 px-3 py-2 border rounded"
          placeholder="Ask the AI..."
        />
        <button onClick={send} className="bg-[var(--primary)] text-white px-4 py-2 rounded">
          Send
        </button>
      </div>
    </div>
  );
};

export default AIAssistant;
